enabled = true
name = "PDRPC"
description = "Discord Rich Presence for Hatsune Miku: Project DIVA Mega Mix+."
version = "0.1.3"
date = "30.07.2022"
author = "Brasileiro"
album_art = true
japanese_names = false
dll = ["PDRPC.dll"]