enabled = true
name = "PDRPC"
description = "Discord Rich Presence for Hatsune Miku: Project DIVA Mega Mix+."
version = "0.1.4"
date = "07.08.2022"
author = "Brasileiro"
album_art = true
japanese_names = false
dll = ["PDRPC.dll"]