enabled = true
name = "PDRPC"
description = "Discord Rich Presence for Hatsune Miku: Project DIVA Mega Mix+."
version = "0.1.9"
date = "31.01.2023"
author = "Brasileiro"
dll = ["PDRPC.dll"]

[settings]
album_art = true
japanese_names = false
show_difficulty = true
song_info_output = false