enabled = true
name = "PDRPC"
description = "Discord Rich Presence for Hatsune Miku: Project DIVA Mega Mix+."
version = "0.0.9"
date = "22.07.2022"
author = "Brasileiro"
dll = ["PDRPC.dll"]
album_art = true
japanese_names = false